### ISSUE TITLE
removing attachments breaks encoding of text body

### ISSUE THREAD

**Issue by rwkstgtd** [dsoares/Roundcube-Plugin-RemoveAttachments#15]
when removing attachments, german special chars get mixed up in text body.
mail-body before action:
Folgende Dateien oder Links können jetzt als Anlage mit Ihrer Nachricht gesendet werden:
mail-body after action:
Folgende Dateien oder Links kÃ¶nnen jetzt als Anlage mit Ihrer Nachricht gesendet werden: 

That is ö is transformed to Ã¶

source-code of mail body before action:
```
Content-Type: text/plain; charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable

Folgende Dateien oder Links k=F6nnen jetzt als Anlage mit Ihrer Nachricht=20
gesendet werden:
```
source-code of mail body after action:
```
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=ISO-8859-1

Folgende Dateien oder Links k=C3=B6nnen jetzt als Anlage mit Ihrer Nachrich=
t
gesendet werden:
```
Could you fix this please? It's very unhandy with german language email messages.

I looked at the source and could not solve the problem, but I noticed something else... is it right, that on text/html the "**text**_encoding" is set, while for text/plain the "**html**_encoding" is set?

            if ($mimetype == 'text/html') {
                $MAIL_MIME->setParam('text_encoding', $part->encoding);
                $MAIL_MIME->setParam('html_charset', $part->charset);
            }
            else if ($mimetype == 'text/plain') {
                $MAIL_MIME->setParam('html_encoding', $part->encoding);
                $MAIL_MIME->setParam('text_charset', $part->charset);
            }

**Comment by dsoares** [comment]
Thank you for reporting this problem. I'll look into it as soon as possible.

**Comment by IzzySoft** [comment]
A year later: Did you find the time to check, @dsoares?

**Comment by dsoares** [comment]
Hi, 
Finally, I'm back to the roundcube plugin projects. I tried to reproduce the issue by sending an email with german text and some attachments but it always returned the correct message and encoding. Maybe it is related with the original encoding of the message.
If any of you @rwkstgtd @IzzySoft @maenujem still has this issue, could you please share with me an email source as example? (message headers and body text at least).
Thank you.

**Comment by maenujem** [comment]
Thanks for the quick response.

Attached is a series of test-emails: PlainText, HTML (here the special characters are encoded using HTML-entities and thus not affected - only its plain-text equivalent), MSHTML - before and after removing an attachment.
[Testmails_before_after-removingAttachment.tar.gz](https://github.com/dsoares/roundcube-removeattachments/files/5611252/Testmails_before_after-removingAttachment.tar.gz)

I'm not sure if the problem occurs in the plugin or if something (charset..) is missing in the object being saved.

**Comment by dsoares** [comment]
Thank you for the examples, I'm going to test the emails tomorrow.

**Comment by dsoares** [comment]
Fixed in [release 0.3.1](/dsoares/roundcube-removeattachments/releases/tag/0.3.1)  @rwkstgtd @IzzySoft @maenujem
Thank you @maenujem for the test emails.

**Comment by IzzySoft** [comment]
Wow, thanks! And apologies I didn't chime in earlier – I had no time to check, drowning in other tasks…

**Comment by maenujem** [comment]
Thank you for the quick reply @dsoares 
I have replaced the plugin by version 0.3.1, but the error is still happening (using my testmails).

**Comment by abcnet-lu** [comment]
Hmmm... I believe nothing to fix this issue has been merged to master nor the release, check https://github.com/dsoares/roundcube-removeattachments/commit/dde775b2cec7032166a5b9fd928b0e33d2e8ce66 it's pretty empty in terms of code.

By the way, I confirm the issue, have the same. Would be nice to reopen the issue.

**Comment by rwkstgtd** [comment]
Don't know much about GitHub, but check out this:
https://github.com/dsoares/roundcube-removeattachments/compare/0.3.0...0.3.1

**Comment by abcnet-lu** [comment]
Hi guys, 
I did a small fix for this, see https://github.com/abcnet-lu/roundcube-removeattachments/pull/1/files 
It works great for me, but there's still an issue if you remove 1 attachment and leave the others, then the name of the remaining attachments are f***** up if they contain special characters.
I will still try to fix this before pushing the fix upstream.
Thank you.

**Comment by Josch-** [comment]
Ok, same here. Installed the plugin today, tried to delete one attachment from an email and after deletion the whole message is broken. Roundcube shows a blank email and my mailer (Apple Mail) shows a plain text mail with broken encoding. The german umlauts look like

m=C3=B6chte - should be möchte

And the mail starts with the lines

Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

Parts of the hidden headers:

Mime-version: 1.0
Content-type: multipart/mixed; boundary="B_3841467769_402013674"

So the encoding definetely breaks when using your plugin.

What do you need to investigate that problem? When you give me an email address i can send you test messages with attachments.
