### ISSUE TITLE
Can't delete attachment from Gmail messages

### ISSUE THREAD

**Issue by nodo50** [dsoares/Roundcube-Plugin-RemoveAttachments#16]
I can't delete a PDF attached in a message comming from a Gmail account.
The PDF is declared as attachment in the message:

Content-Disposition: attachment; filename="calendario-2019-mensual.pdf"

after try to delete without success, it change in the message code to:

Content-Disposition: inline;
 filename=calendario-2019-mensual.pdf;

I tried with messages sent from Thunderbird and Roundcube and I can delete the PDF.
But with differents PDF attached from the Gmail web interface always fails.

I'm using:
Roundcube Webmail 1.2.9
removeattachments 0.2.11
firefox 67.0.4
macOS 10.13.6

thanks in advance

**Comment by dsoares** [comment]
Sorry for the late answer @nodo50 . This issue is now fixed with commit a8afb53.
In the meantime, i'll tag a new release.

**Comment by nodo50** [comment]
Thanks @dsoares 
I have tested it, sorry to inform you that the issue is still presented, the attachment is not deleted.
I tested on a bit old setup:
PHP 5.4.45
Roundcube 1.2.12
removeattachments 0.3.1
Firefox 83.0

Tomorrow I can test it with PHP 5.6

**Comment by nodo50** [comment]
Hi, probably is only related with PHP 5.4.
I have tested in a different server with PHP 5.6 and RC 1.2.12 and your plugin worked fine.

**Comment by kylewong1974** [comment]
I hit the same problem, attachment sent to gmail cannot be deleted. php 7.3 , roundcube 1.5.3
